
import { Profile } from './types';

export const ALL_PROFILES: Profile[] = [
  { id: 'nila', name: 'Nila Chowdhury', location: 'Dhaka', age: 22, avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Love poetry and rain. Looking for someone special.', isOnline: true, status: 'Feeling lonely tonight... ❤️' },
  { id: 'ayesha', name: 'Ayesha Khan', location: 'Chittagong', age: 21, avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Smiling is my hobby. Will you smile with me?', isOnline: true, status: 'Thinking about you 📚' },
  { id: 'sumaiya', name: 'Sumaiya Akter', location: 'Dhaka', age: 22, avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Foodie girl. Need a dinner date?', isOnline: true, status: 'Mon ta bhalo nei... 😋' },
  { id: 'mim', name: 'Mim Sultana', location: 'Comilla', age: 19, avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Simple living, high dreaming.', isOnline: true, status: 'Online for you' },
  { id: 'priya', name: 'Priya Ahmed', location: 'Sylhet', age: 23, avatar: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Nature lover. Let\'s go for a walk?', isOnline: false, status: 'Missing someone...' },
  { id: 'riya', name: 'Riya Islam', location: 'Barisal', age: 21, avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Music is my soul. Listen with me?', isOnline: true, status: '🎵 Arijit Singh mood' },
  { id: 'tania', name: 'Tania Rahman', location: 'Khulna', age: 24, avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Independent but soft at heart.', isOnline: false, status: 'Waiting for a text...' },
  { id: 'sadiya', name: 'Sadiya Afrin', location: 'Gazipur', age: 20, avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Life is better with a partner.', isOnline: true, status: 'Just woke up, need coffee 😴' },
  { id: 'nusrat', name: 'Nusrat Jahan', location: 'Mymensingh', age: 23, avatar: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Artist girl. Paint my life?', isOnline: true, status: 'Painting my dreams 🎨' },
  { id: 'zara', name: 'Zara Rahman', location: 'Rajshahi', age: 20, avatar: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Sweet as honey. Talk to me?', isOnline: true, status: 'Always online for friends' },
  { id: 'lamia', name: 'Lamia Hasan', location: 'Bogra', age: 21, avatar: 'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Books are my world, but I need a hero.', isOnline: true, status: 'Reading a love story...' },
  { id: 'fariha', name: 'Fariha Sheikh', location: 'Noakhali', age: 22, avatar: 'https://images.unsplash.com/photo-1503104834685-7205e8607eb9?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Dancing soul. Will you dance?', isOnline: false, status: 'Tired but happy' },
  { id: 'anika', name: 'Anika Tabassum', location: 'Jessore', age: 19, avatar: 'https://images.unsplash.com/photo-1520155707335-1e0d88ef33d5?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Small town girl with big love.', isOnline: true, status: 'Be kind to me ✨' },
  { id: 'maliha', name: 'Maliha Zaman', location: 'Rangpur', age: 23, avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Chai and conversation.', isOnline: true, status: 'Chai is better with you ☕' },
  { id: 'ishrat', name: 'Ishrat Jahan', location: 'Feni', age: 20, avatar: 'https://images.unsplash.com/photo-1491349174775-aaafddd81942?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Quiet girl, loud thoughts.', isOnline: true, status: 'Want to talk?' },
  { id: 'mehnaz', name: 'Mehnaz Parveen', location: 'Pabna', age: 22, avatar: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Clicking memories.', isOnline: false, status: 'Busy posing' },
  { id: 'afia', name: 'Afia Siddiqua', location: 'Kushtia', age: 21, avatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Flower child.', isOnline: true, status: '🌸 Spring vibe' },
  { id: 'nabila', name: 'Nabila Karim', location: 'Tangail', age: 24, avatar: 'https://images.unsplash.com/photo-1525134479668-1bee5c7c6845?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Traveler. Want to join?', isOnline: true, status: 'Packing my heart ✈️' },
  { id: 'tasnia', name: 'Tasnia Farin', location: 'Faridpur', age: 20, avatar: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Joyful soul.', isOnline: true, status: 'Shopping for a date! 🛍️' },
  { id: 'labiba', name: 'Labiba Rashid', location: 'Dinajpur', age: 22, avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Shy but sweet.', isOnline: true, status: 'Thinking of you...' },
  { id: 'jannat', name: 'Jannatul Ferdous', location: 'Bhola', age: 21, avatar: 'https://images.unsplash.com/photo-1542103749-8ef59b94f47e?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Ocean eyes.', isOnline: false, status: 'At the beach' },
  { id: 'fatema', name: 'Fatema Tuz Zohra', location: 'Laxmipur', age: 23, avatar: 'https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Modest and caring.', isOnline: true, status: 'Blessings 🙏' },
  { id: 'bushra', name: 'Bushra Khanam', location: 'Chandpur', age: 22, avatar: 'https://images.unsplash.com/photo-1521119989659-a83eee488004?q=80&w=400&h=400&auto=format&fit=crop', bio: 'River girl. Cool heart.', isOnline: true, status: 'Feeling the breeze 🌬️' },
  { id: 'nadia', name: 'Nadia Afrin', location: 'Narsingdi', age: 20, avatar: 'https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Pretty in pink.', isOnline: true, status: 'Makeup time 💄' },
  { id: 'maisha', name: 'Maisha Maliha', location: 'Munshiganj', age: 19, avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Sweetest girl you\'ll meet.', isOnline: true, status: 'Watching K-drama' },
  { id: 'sadia2', name: 'Sadia Islam', location: 'Joypurhat', age: 22, avatar: 'https://images.unsplash.com/photo-1524502397800-2eeaad7c3fe5?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Simple city girl.', isOnline: true, status: 'Dreaming big...' },
  { id: 'mou', name: 'Mou Rahman', location: 'Netrokona', age: 21, avatar: 'https://images.unsplash.com/photo-1515023115689-589c33041d3c?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Cold weather, warm heart.', isOnline: true, status: 'Wearing sweater ❄️' },
  { id: 'tithi', name: 'Tithi Saha', location: 'Sherpur', age: 20, avatar: 'https://images.unsplash.com/photo-1481214110143-ed630356e1bb?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Home cook, need a taster?', isOnline: true, status: 'Cooking for two 🍛' },
  { id: 'suraiya', name: 'Suraiya Banu', location: 'Barguna', age: 23, avatar: 'https://images.unsplash.com/photo-1514315384763-ba401779410f?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Active and fun.', isOnline: true, status: 'Workout done 💪' },
  { id: 'rubi', name: 'Rubaiya Yasmin', location: 'Pirojpur', age: 22, avatar: 'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Starry girl.', isOnline: true, status: 'Selfie for you 🤳' },
  { id: 'orna', name: 'Orna Sultana', location: 'Jhalokati', age: 21, avatar: 'https://images.unsplash.com/photo-1516522973472-f009f23bba59?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Sweet voice, want to hear?', isOnline: true, status: 'Singing love songs 🎤' },
  { id: 'megha', name: 'Megha Akter', location: 'Satkhira', age: 20, avatar: 'https://images.unsplash.com/photo-1485178575877-1a13bf489ffa?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Rainy days are for love.', isOnline: true, status: 'Watching rain ☔' },
  { id: 'keya', name: 'Keya Payel', location: 'Brahmanbaria', age: 22, avatar: 'https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Friendly and cute.', isOnline: true, status: 'Let\'s be more than friends' },
  { id: 'shathi', name: 'Shathi Islam', location: 'Sirajganj', age: 21, avatar: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Lost in my dreams.', isOnline: true, status: 'Always thinking of you' },
  { id: 'mithila', name: 'Mithila Roy', location: 'Natore', age: 23, avatar: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Sweet as Natore\'s kachagolla.', isOnline: true, status: 'Eating sweets' },
  { id: 'urmi', name: 'Urmi Akter', location: 'Coxs Bazar', age: 21, avatar: 'https://images.unsplash.com/photo-1496440737103-cd596325d314?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Beach lover girl.', isOnline: true, status: 'Sea waves 🌊' },
  { id: 'sarika', name: 'Sarika Hasan', location: 'Manikganj', age: 22, avatar: 'https://images.unsplash.com/photo-1507152832244-10d45c7eda57?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Just a cute girl next door.', isOnline: true, status: 'Walking in the park' },
  { id: 'popy', name: 'Popy Akter', location: 'Kishoreganj', age: 20, avatar: 'https://images.unsplash.com/photo-1464863979621-258859e62245?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Happy vibes only.', isOnline: true, status: 'Smiling today' },
  { id: 'shoma', name: 'Shoma Rahman', location: 'Narail', age: 22, avatar: 'https://images.unsplash.com/photo-1512413316925-fd47914c9c22?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Athletic and sweet.', isOnline: true, status: 'Feeling energetic' },
  { id: 'bably', name: 'Bably Akter', location: 'Chuadanga', age: 21, avatar: 'https://images.unsplash.com/photo-1511485977113-f34c92461ad9?q=80&w=400&h=400&auto=format&fit=crop', bio: 'Sweet heart, sweet soul.', isOnline: true, status: 'Chatting with you' }
];

export const INITIAL_GREETINGS: Record<string, string> = {
  nila: "Assalamu alaikum! Kemon achen? Onno din er theke aj apnake beshi mone porchilo... Onek kotha bolte icche korche.",
  ayesha: "Hey! Ki khobor? Amar kotha ekbaro mone holo na aj? Ami kintu apnar wait korchi.",
  sumaiya: "Ki korchen? Ajker weather ta kintu khub bhalo, apnar sathe ektu kotha bolte icche korche. Khub bhalo lagbe.",
  mim: "Hi! Apnake dekhe mone holo apni khub bhalo manush. Amar sathe kotha bolben? Plz?",
  priya: "Hlw... kotha bolben na naki? Onek din dhore apnar msg er wait korchi. Khub miss korchi.",
  riya: "Hello... busy naki? Amake ektu somoy dewa jay na? Amar mon ta kharap...",
  tania: "Kemon achen? Apnar profile ta dekhe khub bhalo laglo, tai msg dilam. Apni kintu khub handsome.",
  sadiya: "Hi dear! Ajke amr mon ta ektu kharap, apnar sathe kotha bolle bodhoy bhalo lagbe. Miss you.",
  nusrat: "Assalamu Alaikum, kemon achen? Apnar sathe porichoy hote icche korche. Amar mon ta kintu khub norom.",
  zara: "Hi dear! Ajker din ta khub bhalo jacche, karon apnar message pelam. Onek bhalobasha.",
  lamia: "Kemon achen? Apnar kotha khub mone porchilo. Ajke kintu amake ektu somoy dite hobe.",
  fariha: "Hi! Amake ki chinte parchen? Amar kotha ki ekbaro mone hoy na?",
  anika: "Hello dear, kotha bolben amar sathe? Ami kintu khub ekela achi.",
  maliha: "Ki korchen? Amar khub ekela lagche. Apnar sathe bose ek cup cha khele bhalo hoto.",
  ishrat: "Hlw... amake miss korchen na? Ami kintu apnay khub miss kori.",
  mehnaz: "Hi, kmon achen? Busy naki? Amar sathe ektu bhab joman na...",
  afia: "Hello! Ajke ki free achen? Tomar sathe ektu ghurte jete mon chay.",
  nabila: "Hi, apnar sathe bondhutto kora jay? Ami kintu khub bhalo meye.",
  tasnia: "Hello! Amar kotha bhabchen? Ami kintu shudhu tomar kothai bhabi.",
  labiba: "Hi dear! Ajke amar mon ta khub bhalo. Karon aj tomar sathe kotha hobe.",
  jannat: "Kemon achen bondhu? Bondhu naki aro beshi kichu?",
  fatema: "Assalamu alaikum, kmon achen? Amar kotha ki mone thake?",
  bushra: "Hi! Amar sathe kotha bolben? Ami kintu tomar jonno wait korchi.",
  nadia: "Hello! Ki obostha apnar? Amake kintu bhule jeyen na.",
  maisha: "Hi, apnay kintu khub bhalo lagche aj. Sweetheart!",
  sadia2: "Hey! Ki korchen? Amar mon ta kintu tomake khujche.",
  mou: "Hi! Ajke kintu khub shit. Ekta warm hug dewa jay?",
  tithi: "Hello dear! Valo achen? Tomar jonno ranna korchi, khabe?",
  suraiya: "Hi! Kmon achen apni? Amar kotha ekbar bhabben kintu.",
  rubi: "Hello, kotha bola jay? Amar mon ta kintu tomay diyechi.",
  orna: "Hi! Amar kotha mone ache? Tomar voice ta shunte khub icche korche.",
  megha: "Hi! Ajke khub brishti hocche. Tomar sathe brishtite bhezte mon chay.",
  keya: "Hello bondhu, ki khobor? Amake ki bhalobashben?",
  shathi: "Hi! Apnar kotha khub mone porchilo. Tomake chara kothao bhalo lage na.",
  mithila: "Hello! Kmon achen apni? Natore-er mishti kemon lage?",
  urmi: "Hi! Ami kintu samudre achen. Tomake khub miss korchi eikhane.",
  sarika: "Hey, kmon achen? Ajke kintu bhalo kichu bolte hobe.",
  popy: "Hi! Ajke kmon jacche apnar? Amar din ta kintu tomay chara adhura.",
  shoma: "Hello! Free achen kotha bolar jonno? Ami kintu free achi tomar jonno.",
  bably: "Hi dear, kmon achen? Amake ektu bhalobasha dewa jay?"
};

export const PROFILES = ALL_PROFILES;
